import { Project } from '@/lib/schemas/projects';
import { getProjectImage } from '@/lib/utils/get-project-image';

export const MANUAL_PROJECTS: Project[] = [
  {
    image: getProjectImage('obat'),
    name: 'Obat',
    url: 'https://www.obat.fr/',
    description: 'Construction and finance software as a service with 20K+ users',
    stack: [
      'React',
      'TypeScript',
      'Cypress',
      'Jest',
      'Vitest',
      'TailwindCSS',
      'Redux',
      'Zustand',
      'Storybook',
      'Docker',
      'Tanstack Query',
      'Styled Components',
      'React Hook Form',
      'Framer Motion',
      'JQuery',
      'Supabase',
    ],
    source: 'manual',
  },
  {
    image: getProjectImage('happywait'),
    name: 'Happywait',
    url: 'https://www.happywait.com/',
    description: 'Real estate project management software as a service with 1K+ promoters',
    stack: [
      'React',
      'React Native',
      'TypeScript',
      'Cypress',
      'Jest',
      'Styled Components',
      'Tanstack Query',
      'Zustand',
      'Chakra UI',
      'React Hook Form',
      'Framer Motion',
    ],
    source: 'manual',
  },
  {
    image: getProjectImage('adeo'),
    name: 'Adeo',
    url: 'https://www.adeo.com/',
    description: 'Eco-responsible charity website',
    stack: ['JavaScript', 'SASS', 'Jest', 'GSAP', 'Wordpress'],
    source: 'manual',
  },
  {
    image: getProjectImage('maisondesfemmes'),
    name: 'La maison des femmes',
    url: 'https://www.lamaisondesfemmes.fr/',
    description: 'Non-profit woman rights organization website',
    stack: ['JavaScript', 'SASS', 'Jest', 'GSAP', 'Wordpress'],
    source: 'manual',
  },
  {
    image: getProjectImage('gazettedemonaco'),
    name: 'La gazette de monaco',
    url: 'https://lagazettedemonaco.com/',
    description: 'News platform',
    stack: ['React', 'JavaScript', 'Redux', 'Jest', 'SASS', 'Wordpress'],
    source: 'manual',
  },
  {
    image: getProjectImage('alpinecars'),
    name: 'Alpine cars',
    url: 'https://www.alpinecars.fr/',
    description: 'Car manufacturer website',
    stack: ['JavaScript', 'SASS', 'Wordpress'],
    source: 'manual',
  },
  {
    image: getProjectImage('bluesystems'),
    name: 'Bluesystems',
    url: 'https://www.bluesystems.fr/',
    description: 'Corporate website',
    stack: ['JavaScript', 'SASS', 'Wordpress'],
    source: 'manual',
  },
  {
    image: getProjectImage('ouestfrance'),
    name: 'Ouest France',
    url: 'https://www.ouest-france.fr/',
    description: 'News platform',
    stack: ['JavaScript', 'SASS', 'JQuery', 'Twig'],
    source: 'manual',
  },
  {
    image: getProjectImage('pagesjaunes'),
    name: 'Pages Jaunes',
    url: 'https://www.pagesjaunes.fr/',
    description: 'Business directory platform',
    stack: ['JavaScript', 'SASS', 'JQuery', 'Twig'],
    source: 'manual',
  },
];
