import { TechStack, TechStackEnum } from '@/lib/schemas/projects';
import { BRAND_COLORS } from './colors';
import {
  SiReact,
  SiTypescript,
  SiNextdotjs,
  SiTailwindcss,
  SiChakraui,
  SiMui,
  SiStyledcomponents,
  SiFramer,
  SiGreensock,
  SiReacthookform,
  SiJest,
  SiCypress,
  SiAwsamplify,
  SiAwslambda,
  SiJquery,
  SiWordpress,
  SiSass,
  SiRedux,
  SiNodedotjs,
  SiExpress,
  SiPostgresql,
  SiPrisma,
  SiAngular,
  SiRedis,
  SiNestjs,
  SiReactquery,
  SiSupabase,
  SiMysql,
  SiVitest,
  SiStorybook,
  SiDocker,
  SiLangchain,
  SiJsonwebtokens,
  SiZod,
  SiDrizzle,
  SiSymphony,
} from 'react-icons/si';
import { TbBrandReactNative } from 'react-icons/tb';
import { BiLogoJavascript } from 'react-icons/bi';

interface Technology {
  name: TechStack;
  icon: React.ComponentType<{
    size?: number;
    color?: string;
    className?: string;
  }>;
  color: string;
  url: string;
}

const ICONS: Record<
  TechStack,
  React.ComponentType<{ size?: number; color?: string; className?: string }>
> = {
  Angular: SiAngular,
  Primeng: SiReact,
  Redis: SiRedis,
  Neon: SiPostgresql,
  React: SiReact,
  'Next.js': SiNextdotjs,
  'Nest.js': SiNestjs,
  'Express.js': SiExpress,
  TypeScript: SiTypescript,
  JavaScript: BiLogoJavascript,
  'React Native': TbBrandReactNative,
  Redux: SiRedux,
  Zustand: SiReact,
  'Tanstack Query': SiReactquery,
  TailwindCSS: SiTailwindcss,
  SASS: SiSass,
  'Styled Components': SiStyledcomponents,
  'Material UI': SiMui,
  Supabase: SiSupabase,
  'Chakra UI': SiChakraui,
  Shadcn: SiReact,
  'Framer Motion': SiFramer,
  GSAP: SiGreensock,
  'React Hook Form': SiReacthookform,
  Protobuf: SiReact,
  'Node.js': SiNodedotjs,
  PostgreSQL: SiPostgresql,
  MySQL: SiMysql,
  Jest: SiJest,
  Vitest: SiVitest,
  Storybook: SiStorybook,
  Cypress: SiCypress,
  Docker: SiDocker,
  'AWS Lambda': SiAwslambda,
  'AWS Amplify': SiAwsamplify,
  JQuery: SiJquery,
  Twig: SiSymphony,
  Wordpress: SiWordpress,
  Langchain: SiLangchain,
  Prisma: SiPrisma,
  JWT: SiJsonwebtokens,
  'Radix UI': SiReact,
  Upstash: SiReact,
  Zod: SiZod,
  Drizzle: SiDrizzle,
};

const COLORS: Record<TechStack, string> = {
  Angular: '#DD0031',
  Primeng: '#007bff',
  Redis: '#DC382D',
  Neon: BRAND_COLORS.postgresql,
  React: BRAND_COLORS.react,
  'Next.js': BRAND_COLORS.nextjs,
  'Nest.js': BRAND_COLORS.nestjs,
  'Express.js': BRAND_COLORS.express,
  TypeScript: BRAND_COLORS.typescript,
  JavaScript: BRAND_COLORS.javascript,
  'React Native': BRAND_COLORS.react,
  Redux: BRAND_COLORS.redux,
  Zustand: '#000000',
  'Tanstack Query': '#FF4154',
  TailwindCSS: BRAND_COLORS.tailwind,
  SASS: BRAND_COLORS.sass,
  'Styled Components': BRAND_COLORS.styledComponents,
  'Material UI': BRAND_COLORS.materialui,
  Supabase: '#3ECF8E',
  'Chakra UI': BRAND_COLORS.chakra,
  Shadcn: '#000000',
  'Framer Motion': BRAND_COLORS.framer,
  GSAP: BRAND_COLORS.gsap,
  'React Hook Form': BRAND_COLORS.reactHookForm,
  Protobuf: '#000000',
  'Node.js': BRAND_COLORS.nodejs,
  PostgreSQL: BRAND_COLORS.postgresql,
  MySQL: '#4479A1',
  Jest: BRAND_COLORS.jest,
  Vitest: '#6E9F18',
  Storybook: '#FF4785',
  Cypress: BRAND_COLORS.cypress,
  Docker: BRAND_COLORS.docker,
  'AWS Lambda': BRAND_COLORS.awsLambda,
  'AWS Amplify': BRAND_COLORS.awsAmplify,
  JQuery: BRAND_COLORS.jquery,
  Twig: BRAND_COLORS.twig,
  Wordpress: BRAND_COLORS.wordpress,
  Langchain: '#000000',
  Prisma: '#2D3748',
  JWT: '#000000',
  'Radix UI': '#000000',
  Upstash: '#000000',
  Zod: '#3E6F9E',
  Drizzle: '#A3BF46',
};

const URLS: Record<TechStack, string> = {
  Angular: 'https://angular.io',
  Primeng: 'https://primeng.org/',
  Redis: 'https://redis.io',
  Neon: 'https://neon.tech',
  React: 'https://react.dev',
  'Next.js': 'https://nextjs.org',
  'Nest.js': 'https://nestjs.com',
  'Express.js': 'https://expressjs.com',
  TypeScript: 'https://www.typescriptlang.org',
  JavaScript: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
  'React Native': 'https://reactnative.dev',
  Redux: 'https://redux.js.org',
  Zustand: 'https://zustand-demo.pmnd.rs/',
  'Tanstack Query': 'https://tanstack.com/query/latest',
  TailwindCSS: 'https://tailwindcss.com',
  SASS: 'https://sass-lang.com',
  'Styled Components': 'https://styled-components.com',
  'Material UI': 'https://mui.com',
  Supabase: 'https://supabase.io',
  'Chakra UI': 'https://chakra-ui.com',
  Shadcn: 'https://ui.shadcn.com/',
  'Framer Motion': 'https://www.framer.com/motion/',
  GSAP: 'https://greensock.com/gsap/',
  'React Hook Form': 'https://react-hook-form.com',
  Protobuf: 'https://developers.google.com/protocol-buffers',
  'Node.js': 'https://nodejs.org',
  PostgreSQL: 'https://www.postgresql.org',
  MySQL: 'https://www.mysql.com',
  Jest: 'https://jestjs.io',
  Vitest: 'https://vitest.dev',
  Storybook: 'https://storybook.js.org',
  Cypress: 'https://www.cypress.io',
  Docker: 'https://www.docker.com',
  'AWS Lambda': 'https://aws.amazon.com/lambda',
  'AWS Amplify': 'https://aws.amazon.com/amplify',
  JQuery: 'https://jquery.com',
  Twig: 'https://twig.symfony.com',
  Wordpress: 'https://wordpress.org',
  Langchain: 'https://www.langchain.com/',
  Prisma: 'https://www.prisma.io',
  JWT: 'https://jwt.io',
  'Radix UI': 'https://www.radix-ui.com/',
  Upstash: 'https://upstash.com',
  Zod: 'https://zod.dev',
  Drizzle: 'https://orm.drizzle.team',
};

export const TECHNOLOGIES: Technology[] = TechStackEnum.options.map(tech => ({
  name: tech,
  icon: ICONS[tech],
  color: COLORS[tech],
  url: URLS[tech],
}));
