import { z } from 'zod';
import { StaticImageData } from 'next/image';

export const TechStackEnum = z.enum([
  'Angular',
  'Primeng',
  'Redis',
  'Neon',
  'React',
  'Next.js',
  'Nest.js',
  'Express.js',
  'TypeScript',
  'JavaScript',
  'React Native',
  'Redux',
  'Zustand',
  'Tanstack Query',
  'TailwindCSS',
  'SASS',
  'Styled Components',
  'Material UI',
  'Supabase',
  'Chakra UI',
  'Shadcn',
  'Framer Motion',
  'GSAP',
  'React Hook Form',
  'Protobuf',
  'Node.js',
  'PostgreSQL',
  'MySQL',
  'Jest',
  'Vitest',
  'Storybook',
  'Cypress',
  'Docker',
  'AWS Lambda',
  'AWS Amplify',
  'JQuery',
  'Twig',
  'Wordpress',
  'Langchain',
  'Prisma',
  'JWT',
  'Radix UI',
  'Upstash',
  'Zod',
  'Drizzle',
]);

export const ProjectSchema = z.object({
  image: z.custom<StaticImageData>(),
  name: z.string(),
  description: z.string().optional(),
  github: z.string().url().optional(),
  url: z.string().url().optional(),
  stack: z.array(TechStackEnum),
});

export type TechStack = z.infer<typeof TechStackEnum>;
export type Project = z.infer<typeof ProjectSchema>;
